### ISSUE TITLE
Permission denied, open '/usr/local/.git/hooks/pre-commit'

### ISSUE THREAD

**Issue by zhuolikevin** [cxtom/fecs-git-hooks#3]
运行 sudo npm install fecs-git-hooks -g的时候遇到的问题

```
/usr/local/bin/fecs-hook -> /usr/local/lib/node_modules/fecs-git-hooks/bin/fecs-hook                                   │| |/  
                                                                                                                       │| *   02f091b - Merge pull request #24 from nicoder/patch-1 (7 months ago) <Ruan YiFeng>
> fecs-git-hooks@0.1.1 install /usr/local/lib/node_modules/fecs-git-hooks                                              │| |\  
> fecs -v && node ./lib/install.js                                                                                     │| | * 82b24f7 - fix typo (7 months ago) <Nicolas Dermine>
                                                                                                                       │* | | 326c77a - edit Readme (7 months ago) <ruanyf>
fecs 0.8.5-beta.9                                                                                                      │|/ /  
Trace: { [Error: EACCES: permission denied, open '/usr/local/.git/hooks/pre-commit']                                   │* |   56c16bb - Merge pull request #23 from luoxiaobatman/master (7 months ago) <Ruan YiFeng>
  errno: -13,                                                                                                          │|\ \  
  code: 'EACCES',                                                                                                      │| |/  
  syscall: 'open',                                                                                                     │|/|   
  path: '/usr/local/.git/hooks/pre-commit' }                                                                           │| * aaf1144 - fix readme (7 months ago) <luoxiao>
    at Object.<anonymous> (/usr/local/lib/node_modules/fecs-git-hooks/lib/install.js:14:13)                            │|/  
    at Module._compile (module.js:413:34)                                                                              │*   b3dd15d - Merge pull request #20 from qiuyuntao/master (8 months ago) <Ruan YiFeng>
    at Object.Module._extensions..js (module.js:422:10)                                                                │|\  
    at Module.load (module.js:357:32)                                                                                  │| * fc03b25 - lack of a comma in demo 15 webpack.config.js (8 months ago) <yuntao.qyt>
    at Function.Module._load (module.js:314:12)                                                                        │Kevin at Mac.local in ~/workspace/webpack-demos on master
    at Function.Module.runMain (module.js:447:10)                                                                      │$ tig
    at startup (node.js:141:18)                                                                                        │Kevin at Mac.local in ~/workspace/webpack-demos on master
    at node.js:933:3 
```

**Comment by zhuolikevin** [comment]
好像把 /usr/local/.git/hooks权限改成777就可以了

**Comment by cxtom** [comment]
这个确实有问题，在全局安装是不需要复制 hook 的，得改下
